'''
Setup file for aftershoq: Installs all dependencies and modifies sysetm path.

@author: Martin Franckie

'''
from setuptools import setup, find_packages
from setuptools.command.install import install
import os

class InstallWrapper(install):

    def run(self):
        print("Wrapper fixing external module 'hilbert_curve'")
        self.initModules()
        install.run(self)

    def initModules(self):
        path = os.getcwd() + "/hilbert_curve/"
        with open(path + "__init__.py", 'w') as f:
           f.write("# generated by aftershoq installer")


setup(
    name="aftershoq",
    author = "Martin Franckie",
    version = "0.1",
    author_email = "martin.franckie@phys.ethz.ch",
    url = "https://github.com/mfranckie/aftershoq",
    packages=find_packages(),
    install_requires=['numpy', 
                      'scipy', 
                      'matplotlib',
                      'lxml'],
    cmdclass = {'install':InstallWrapper}
    )
